version: "3"
services:
  desktop:
    build: ./
    working_dir: /voicevox
    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix/
    environment:
      - DISPLAY=$DISPLAY
    tty: true
    stdin_open: true
    networks:
      - host
