version: "3"
services:
  desktop:
    network_mode: host
    image: eggplanter/voicevox_desktop
    working_dir: /voicevox
    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix/
    environment:
      - DISPLAY=${DISPLAY}
    tty: true
    stdin_open: true
